### ISSUE TITLE
[Fire TV Stick] Crash on launch: java.lang.NoClassDefFoundError: mozilla.components.browser.engine.system.matcher.UrlMatcher$2

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1087]
Build master: e20111a7d0b64b57d4b6beccfa2709e15778d261

Build variant: debug

Launched on a Fire TV stick, I see the first user-interactable view to toggle turbo mode and then the application crashes.

First logged with

> I/art: Rejecting re-init on previously-failed class java.lang.Class<mozilla.components.browser.engine.system.matcher.UrlMatcher$2>

and then

```
E/AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-2
                  Process: org.mozilla.tv.firefox.debug, PID: 7619
                  java.lang.NoClassDefFoundError: mozilla.components.browser.engine.system.matcher.UrlMatcher$2
                      at mozilla.components.browser.engine.system.matcher.UrlMatcher.<init>(UrlMatcher.kt:61)
                      at mozilla.components.browser.engine.system.matcher.UrlMatcher$Companion.createMatcher(UrlMatcher.kt:213)
                      at mozilla.components.browser.engine.system.matcher.UrlMatcher$Companion.createMatcher(UrlMatcher.kt:186)
                      at mozilla.components.browser.engine.system.SystemEngineView$Companion.getOrCreateUrlMatcher$engine_system_release(SystemEngineView.kt:241)
                      at mozilla.components.browser.engine.system.SystemEngineSession$enableTrackingProtection$1$1.doResume(SystemEngineSession.kt:115)
```

**Comment by liuche** [comment]
I just bisected this to 123b3d128.

**Comment by npark-mozilla** [comment]
This is the new bug that blocks the UI Test fix work :)

**Comment by csadilek** [comment]
This is caused by Android components. `UrlMatcher` is incorrectly using Java 8's Map.forEach which seems to cause this. I've filed https://github.com/mozilla-mobile/android-components/issues/750 to address this.

**Comment by liuche** [comment]
Okay, looks like it's already merged in so it'll get fixed by updating to a-c 0.23 in #1076 - duping to there.

**Comment by liuche** [comment]
@npark-mozilla can the tests be run only on Android 25? afaik this only affects Android 22, which is the stick.
